spring:
  data:
    mongodb:
      uri: ${DB_URI:}
      database: ${DB_NAME:ssa}

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:}

aws:
  active-profile: ${AWS_PROFILE:}
  region: ${AWS_REGION:eu-central-1}
  s3:
    image-bucket: ${S3_IMAGES_BUCKET:ssa-user-images}
    thumbnail-bucket: ${S3_THUMBNAILS_BUCKET:ssa-image-thumbnails}
